CI does not stop on report fail

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -161,14 +161,14 @@ runs:
                   $image_url/$name:${{ github.sha }} \
                   --image-user=$(cat USERNAME) --image-token=$(cat PASSWORD) \
                   --space-username=${{ inputs.space_username }} --space-password=${{ inputs.space_password }} --space-org=${{ inputs.org_id }} \
-                  ${{ inputs.api_url }} || { echo "::warning::Failed to report" ; errors+=("${name}") ; continue ;}
+                  ${{ inputs.api_url }} || { echo "::warning::Failed to report" ; errors+=("${name}") ;}
                 else
                   echo "without credentials"
                   space ci report ./$dir ${{ steps.extract_branch.outputs.branch }} \
                   ${{ github.sha }} "$(git log | grep -P "commit [a-z0-9]{40}" -m 1 | cut -d ' ' -f2 | git log --format=%B -n 1)" done \
                   $image_url/$name:${{ github.sha }} \
                   --space-username=${{ inputs.space_username }} --space-password=${{ inputs.space_password }} --space-org=${{ inputs.org_id }} \
-                  ${{ inputs.api_url }} || { echo "::warning::Failed to report ${name}" ; errors+=("${name}") ; continue ;}
+                  ${{ inputs.api_url }} || { echo "::warning::Failed to report ${name}" ; errors+=("${name}") ;}
                 fi  
               if [[ ${{ inputs.build }} == true ]];
               then
