removed duplicate commands

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -163,24 +163,26 @@ runs:
                 echo "Pushing ${name}"
                 docker push -q --all-tags $image_url/$name || { echo "::warning::Failed to push ${name}" ; errors+=("${name}") ; continue ;}
               fi
-              echo -n "Testing ${name} "  
+              echo -n "Testing ${name} "
+              bash_cmd="space ci report ./$dir ${{ steps.extract_branch.outputs.branch }} \
+                  $commit_sha "$(echo $commit_sha | git log --format=%B -n 1)" done \
+                  $image_url/$name:$commit_sha \
+                  --space-username=${{ inputs.space_username }} --space-password=${{ inputs.space_password }}"
               if [[ ${{ inputs.username }} == "$(cat USERNAME)" ]] && [[ ${{ inputs.password }} == "$(cat PASSWORD)" ]];
               then
-                echo "with credentials"
-                space ci report ./$dir ${{ steps.extract_branch.outputs.branch }} \
-                $commit_sha "$(echo $commit_sha | git log --format=%B -n 1)" done \
-                $image_url/$name:$commit_sha \
-                --image-user=$(cat USERNAME) --image-token=$(cat PASSWORD) \
-                --space-username=${{ inputs.space_username }} --space-password=${{ inputs.space_password }} --space-org="${{ inputs.org_id }}" \
-                ${{ inputs.api_url }} || { echo "::warning::Failed to report" ; errors+=("${name}") ; continue ;}
+                echo -n "with credentials "
+                bash_cmd="${bash_cmd} --image-user=$(cat USERNAME) --image-token=$(cat PASSWORD)"
               else
                 echo "without credentials"
-                space ci report ./$dir ${{ steps.extract_branch.outputs.branch }} \
-                $commit_sha "$(git log | grep -P "commit [a-z0-9]{40}" -m 1 | cut -d ' ' -f2 | git log --format=%B -n 1)" done \
-                $image_url/$name:$commit_sha \
-                --space-username=${{ inputs.space_username }} --space-password=${{ inputs.space_password }} --space-org="${{ inputs.org_id }}" \
-                ${{ inputs.api_url }} || { echo "::warning::Failed to report ${name}" ; errors+=("${name}") ; continue ;}
-                fi  
+              fi  
+              if [[ ${{ inputs.org_id }} != 'None' ]];
+              then
+                echo "with org"
+                bash_cmd="${bash_cmd} --space_org=${{ inputs.org_id }}"
+              else
+                echo "without org"
+              fi
+              bash -c "${bash_cmd} ${{ inputs.api_url }}" || { echo "::warning::Failed to report" ; errors+=("${name}") ; continue ;}
               if [[ ${{ inputs.build }} == true ]];
               then
                 echo "Tagging ${name} as latest and pushing"
